/* FILE: js/components/render/renderConfig.js */

export const DOM_CONFIG = {
  IDS: {
    PROFILE_IMG: "profile-img",
    PROFILE_IMG_ABOUT: "profile-img-about",
    ABOUT_CONTAINER: "about-container",
    ABOUT_TEXT_TARGET: "about-text-target",
    SOCIAL_DOCK_TARGET: "social-dock-target",
    SERVICES_CONTAINER: "services-container",
    PROJECTS_CONTAINER: "projects-container",
    SOCIAL_CONTAINER: "social-container",
    SOCIAL_CONTAINER_ABOUT: "social-container-about",
  },
  CLASSES: {
    LOADED: "loaded",
    SERVICE_CARD: "service-card glass-panel",
    PROJECT_ROW: "project-row glass-panel",
    DOCK_ICON: "dock-icon",
    SOCIAL_LINK: "social-link",
    VISIBLE: "in-view",
    PROJECT_INFO: "project-info",
    PROJECT_HEADER: "project-header",
    PROJECT_TITLE: "project-title",
    TECH_STACK: "tech-stack",
    TECH_BADGE: "tech-badge",
    PROJECT_DESC: "project-desc",
    PROJECT_LINK: "project-link",
    SERVICE_ICON_WRAPPER: "service-icon-wrapper",
    SERVICE_CONTENT: "service-content",
    CARD_HEADER: "card-header",
    STATUS_DOT: "status-dot",
    CARD_BODY: "card-body",
    CORNER_BRACKET: "corner-bracket",
    SPEC_ITEM: "spec-item",
    SPEC_LABEL: "spec-label",
    SPEC_VALUE: "spec-value",
    SPEC_ICON: "spec-icon",
    ABOUT_VISUAL: "about-visual",
    PILOT_CARD: "pilot-card",
    PILOT_PHOTO: "pilot-photo",
    PILOT_STATUS: "pilot-status",
    ABOUT_DATA: "about-data",
    BIO_TEXT: "bio-text",
    SPECS_TITLE: "specs-title",
    SPECS_GRID: "specs-grid",
    SOCIAL_DOCK_CONTAINER: "social-dock-container",
    SOCIAL_DOCK_LABEL: "social-dock-label",
    SOCIAL_DOCK: "social-dock",
  },
};
